pub mod aws;
pub mod config;
pub mod session;
pub mod monitor;
pub mod reconnect;
pub mod manager;
pub mod performance;
pub mod health;
pub mod resource;
pub mod persistence;
pub mod ui;
pub mod error;
pub mod error_recovery;
pub mod logging;
pub mod user_messages;
pub mod multi_session;
pub mod multi_session_ui;
pub mod vscode;
pub mod diagnostic;
pub mod instance_diagnostics;
pub mod port_diagnostics;
pub mod ssm_agent_diagnostics;
pub mod iam_diagnostics;
pub mod network_diagnostics;
pub mod auto_fix;
pub mod suggestion_generator;
pub mod preventive_check;
pub mod report_manager;
pub mod aws_config_validator;
pub mod diagnostic_feedback;
pub mod realtime_feedback;

pub use config::Config;
pub use error::{Ec2ConnectError, Result};
pub use session::{Session, SessionStatus, SessionConfig};
pub use vscode::{VsCodeIntegration, VsCodeConfig, ConnectionInfo};
pub use diagnostic::{DiagnosticManager, DefaultDiagnosticManager, DiagnosticConfig, DiagnosticResult, DiagnosticStatus, Severity, DiagnosticProgress};
pub use instance_diagnostics::{InstanceDiagnostics, DefaultInstanceDiagnostics, InstanceInfo, InstanceStateInfo, PlatformInfo};
pub use port_diagnostics::{PortDiagnostics, DefaultPortDiagnostics, PortInfo, ProcessInfo, PortSuggestion, PortReservation};
pub use ssm_agent_diagnostics::{SsmAgentDiagnostics, DefaultSsmAgentDiagnostics, SsmAgentInfo, RegistrationStatus, PingStatus};
pub use iam_diagnostics::{IamDiagnostics, DefaultIamDiagnostics, IamInfo, PolicyInfo, PolicyType, CredentialsStatus};
pub use network_diagnostics::{NetworkDiagnostics, DefaultNetworkDiagnostics, VpcEndpointInfo, SecurityGroupRule, RouteTableInfo, ConnectivityTestResult};
pub use auto_fix::{AutoFixManager, DefaultAutoFixManager, FixAction, FixResult, FixActionType, RiskLevel};
pub use suggestion_generator::{SuggestionGenerator, DefaultSuggestionGenerator, FixSuggestion, ProblemSeverity};
pub use preventive_check::{PreventiveCheck, DefaultPreventiveCheck, PreventiveCheckConfig, PreventiveCheckResult, PreventiveCheckStatus, ConnectionLikelihood};
pub use report_manager::{ReportManager, DiagnosticReport, DiagnosticSummary, ReportFormat, OverallStatus, ReportManagerConfig, AwsApiError, NetworkDiagnosticDetails};
pub use aws_config_validator::{AwsConfigValidator, DefaultAwsConfigValidator, AwsConfigValidationConfig, AwsConfigValidationResult, ValidationCheckResult, ComplianceStatus, ValidationSummary, ImprovementSuggestion, SuggestionCategory, SuggestionPriority};
pub use diagnostic_feedback::{DiagnosticFeedbackSystem, FeedbackState, FeedbackEvent, ConfirmationRequest, FeedbackDisplayConfig};
pub use realtime_feedback::{RealtimeFeedbackManager, FeedbackConfig, FeedbackStatus, create_progress_callback, create_result_callback};